LABSN/mnefun

.gitignore, bin/simulate_movement.py, examples/funloc/analysis_fun.py, examples/plot_simulation.py, mnefun/_mnefun.py, mnefun/_paths.py, mnefun/_scoring.py, mnefun/_status.py, mnefun/run_sss.sh
Should be working, but I need to test it out and change the example to use it.
=> ENH: Spheres

mnefun/_mnefun.py, mnefun/_simulate.py
@kambysese can you see if this works for you?
=> FIX: Fix imports

mnefun/_simulate.py
Closes #74.
Closes #75.
@staulu can you try this branch to see if it works for you? You can follow the `git` helper document on Maintainers here:
https://github.com/LABSN/expyfun/blob/master/git_flow.rst#maintainers
If you don't feel like messing with `git`, I can have someone review the changes and merge into `master`, and we can iterate that way.
cc @wronk you will want to make these sorts of changes in your mne-python PR, too. Notably, I didn't do any protection for MEG-only or EEG-only before. This adds checks for MEG-only. In the EEG-only case, we don't even have to simulate head positions, which is nice. Please add a note to yourself somewhere (probably on GitHub in your PR) to make sure MEG-only, EEG-only, and MEG+EEG all work.
=> FIX: Better error msgs

mnefun/_mnefun.py, setup.py
@Eric89GXL please merge, thanks.
=> fix: externals packaging and Epochs decimation argument 

mnefun/_mnefun.py, mnefun/run_sss.sh
@kambysese sorry to steal your PR, but I need this functionality actually. See if this solves your use case. It adds two things:
1. Translating all runs from all *subjects* to the same head position.
2. Adding arbitrary maxfilter argumenst, e.g. `params.mf_args = '-hpie 10 -hpig 0.9 -corr 0.9'` for subjects with less accurate HPI.
=> ENH: Allow extra maxfilter args

mnefun/_simulate.py
@staulu see if this fixes the event issue for you.
=> FIX: Fix for newer mne-python and event len

mnefun/_mnefun.py, mnefun/_paths.py, mnefun/_scoring.py, mnefun/_status.py
@jyeatman see if this solves your use case. You can now do:
```
p.subject_run_indices = [None, [0, 1, 3, 4]]
```
This would use all runs for subject 0, and runs 0, 1, 3, and 4 for subject 1.
I am currently testing that the example code still works, but hopefully it will work for you already.
=> ENH: Allow run indices to be provided

mnefun/_mnefun.py
@Eric89GXL this tries to improve handling of ExG event files based on their availability during plotting raw data subsequent to preprocessing. It worked without error on my data with just EOG events as well as example data. However for some reason the plot is not being shown for some reason in my IDE, I am assuming some resurfacing pyplot and/or matplotlib backend issue. Can you run with example analysis with `params.plot_raw=True`?
=> FIX:raw plotting

mnefun/_mnefun.py
@Eric89GXL blocking behavior for psd plots. 
@jyeatman can you try this out to see if it works?
=> FIX:additional plot window process blocking behavior.

mnefun/__init__.py, mnefun/_mnefun.py, mnefun/_status.py, mnefun/run_sss.sh
Adds an entry point for custom projectors, along with a couple other minor options.
=> FIX: Extra parameters, custom proj

mnefun/_mnefun.py
@Eric89GXL I think this is working now, will continue to test with infant data. @mdclarke what was the bad_baby subject giving you an error for median hp calc?
=> Check rotation matrix is special orthogonal

mnefun/_mnefun.py
@Eric89GXL please review encountered import error on mne-python after updating both repos to current master.
=> fixed import error

mnefun/_mnefun.py
=> ENH: minor add baseline to mne-python reporting

mnefun/_mnefun.py
@Eric89GXL minor touch up if you're ok with syntax.
=> FIX: minor assertion to cover args

mnefun/_mnefun.py
@Eric89GXL hopefully a quick merge.
=> Minor type checking & doc fix

mnefun/_mnefun.py
=> FIX doc string

mnefun/_mnefun.py
@Eric89GXL should I be concerned about backward compatibility here?
=> Minor fix to squash deprecation error

bin/run_mne_bem.py
Fixes including PEP 8, doc string, and addition of `kwarg` for grid point 'spacing' in source space.Tested and ready for merge from my end.
=> Little house keeping

.gitignore, mnefun/_mnefun.py
@Eric89GXL this change works with the example ds. LMKWYT. If go for merge then I can test with Alexis' dataset. Also, a couple of automated PEP8 fixes snuck in. LMK if you have a problem with them.
=> Safer file name handling during fetch

mnefun/_mnefun.py
@kambysese fixes a few things that were broken recently due to `mnefun` Maxwell-filtering changes as well as `mne-python` updates. Ready for review from my end.
=> FIX: Minor fixes

mnefun/_mnefun.py
@kambysese your recent changes broke my pulls :( Can you see if this works for you?
=> FIX: Minor fix to filename

examples/funloc/analysis_fun.py
Bolster comments for bits I didn't understand at first
=> Add documentation to primary `funloc` example

bin/chpi_snr.py, bin/plot_chpi_snr.py, examples/chpi_snr_command_line.py, mnefun/__init__.py, mnefun/_mnefun.py, setup.py
I had to modify sys.path in the beginning of the executable script to import mnefun. Let me know if you prefer some other solution.
=> refactor into mnefun / bin

bin/plot_chpi_snr.py, mnefun/_mnefun.py
WIth my test data, results are almost identical with using just a couple of harmonics. Still it's probably a good default.
=> use harmonics up to lowpass by default

mnefun/_mnefun.py
=> FIX autobad channel detection without eeg average reference projection

.gitignore, mnefun/_mnefun.py, mnefun/tests/test_events.py, mnefun/tests/test_save_epochs.py
=> [ENH] Save_epochs fail gracefully if no epochs left.

mnefun/_mnefun.py, mnefun/_scoring.py
This should make progress for subjects a bit smoother.
@kambysese can you try it with some new subject when you get a chance?
=> ENH: Smoother flow

mnefun/_mnefun.py
=> FIX: minor version conflict with mnepy deprecation

examples/funloc/analysis_fun.py, mnefun/_mnefun.py
=> Try fetching data from multiple mounting points on sinuhe acq machine

mnefun/_mnefun.py
@Eric89GXL this looks to be a conflict
=> FIX:minor invalid arg to epochs.equalize_event_counts

.gitignore, examples/funloc/mnefun-demo.ipynb
@Eric89GXL for some reason I had to remove `funloc` as ignored directory in `.gitignore` and redo the whole PR
=> Demo notebook

mnefun/_mnefun.py
=> Fix plot psd

mnefun/_mnefun.py
@Eric89GXL @staulu asked to median traces in plots generated by `plot_chpi_snr_raw`. If you're ok with this, could you give me a clue as to add `--- Median` to the two legends in question.
=> ENH: plot chpi_snr medians

mnefun/_mnefun.py
This fixes a "double indexing" bug, where MEG channels were already picked into a 306-dim matrix and then again indexed with `pick_grad` and `pick_mag`. It manifested as an IndexError in a case where the fiff channel list did not start with MEG channels.
=> fix indexing bug

.gitignore, examples/funloc/analysis_fun.py, mnefun/_mnefun.py
@Eric89GXL maybe go with this for now for generating head movement plot. WDYT?
=> Make plots

mnefun/_mnefun.py
Some minor fixes for latest MNE.
=> MRG: Updates for latest MNE

mnefun/_mnefun.py
Prevent drop_logs plots windows popping up after  do_preprocessing in large batch jobs
=> FIX default drop_logs plots behavior

mnefun/_mnefun.py
=> ENH allow user defined Neuromag site files

mnefun/_mnefun.py
@Eric89GXL super minor string formatting fix
=> Minor fix string formatting

mnefun/_mnefun.py
@Eric89GXL filename arg is deprecated and causing issues in `mne.setup_source_space`
=> FIX mne setup_source_spaces version conflict

mnefun/_mnefun.py
Closes #179.
@kambysese can you see if this fixes your problem?
=> FIX: Fix proj

mnefun/_mnefun.py
=> Improve assertion error message

mnefun/__init__.py, mnefun/_mnefun.py
`fig = mnefun.plot_good_coils(raw)` does this:
=> WIP: Add coil distance plot

mnefun/__init__.py, mnefun/_mnefun.py
=> WIP: Add compute_auc

examples/funloc/analysis_fun.py, mnefun/_mnefun.py
@larsoner please review. And do you think you could test on funloc sample data once we agree on implementation?
=> ENH:add autoreject channel thresholds to epoching

mnefun/__init__.py, mnefun/_mnefun.py
@nfoti can you see if this works for you? I've only really tested it with the `HCPMMP1_combined` parcellation.
=> ENH: Add label combining

mnefun/_mnefun.py
=> FIX: Fix for Spyder

mnefun/_mnefun.py
@mdclarke try this.
Closes #193.
=> fix additional subprocess io streams

mnefun/_mnefun.py
@larsoner please review and confirm loose/free/fixed source ori parameters. Fixes #191
=> Fix fwd & inverse compatibility issues.

.gitignore, mnefun/_mnefun.py
@larsoner couple questions with this one:
1. Wasn't sure about what you discussed with @mdclarke wrt to `pos` argument for `setup_volume_source_space` but I went with `pos=7.0` rather than a dictionary. If you know what `pos[‘rr’]` and `pos[‘nn’]` should look like then I can change that.
2. LMK how you want to handle trans for volumetric sourcespace. `make_forward_solution` seems to expect `type` mne.transforms.Transform class and not a dict. This seems to contradict [docstring](https://martinos.org/mne/stable/generated/mne.make_forward_solution.html)
=> WIP fix make volumetric source space for sphere

examples/funloc/analysis_fun.py, mnefun/_mnefun.py
@ktavabi can you give this a try with your data and see if it works? If you can post a previous (on `master`) alignment and the alignment using this PR that would help verify it's working properly.
=> ENH: Add time-weighted average head position

examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_report.py
@ktavabi can you give this a try with some of your data and see if it's helpful? I always want to look at N100 localization in adults, and this makes it easy to do in the report.
Right now it only works with surface-based source estimates.
=> ENH: Add source loc to Report

mnefun/_reorder.py
@mdclarke can you see if this fixes your problem?
=> FIX: Fix anon

examples/funloc/analysis_fun.py, mnefun/_mnefun.py
@larsoner please review. Fixes #206
=> FIX trial rejection criteria computed by Autoreject module.

examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_report.py
Todo before merge:
- ~~[ ] Check for unreasonable head positions by fitting a sphere and checking for sensor collisions~~
=> WIP: Add annotations

examples/funloc/analysis_fun.py, mnefun/_paths.py, mnefun/_report.py
=> ENH file checks

examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_report.py
@ktavabi I have made some improvements to the cHPI fitting and annotations that might help. When you get a chance, can you try this on the subject who ended up with ~6 usable trials after adding annotations:
1. make a note of how many epochs you currently have (6?)
2. update to latest `mne` (so that it includes some recent cHPI fixes)
3. switch to this PR on `mnefun`
4. delete the `raw_fif/*-annot.fif` and `raw_fit/*-counts.h5` files, if they exist
5. delete the `raw_fif/*twa_pos.fif` files
6. rerun the subject's steps from Maxfilter onward (`do_sss`, `fetch_sss`, `do_ch_fix`, `gen_ssp`, `apply_ssp`, `write_epochs`), noting what percentage of trials are dropped for what reason
7. note how many epochs you end up with
8. Repeat steps 4-7 after setting `p.coil_dist_limit = 0.01` and see if …
=> WIP: Better good check

Makefile, mnefun/_mnefun.py, mnefun/_report.py
@ktavabi this contains some little fixes for head position plotting, and adds `__pycache__` deletion so you can do `make clean` in the future when necessary. Can you see if it works for you?
Closes #219
=> Tweak lims

examples/funloc/analysis_fun.py, mnefun/_mnefun.py
@larsoner also fixes #224 by adding docstring.
=> ENH: Compute noise covar rank during inverse

mnefun/_mnefun.py, mnefun/_report.py
Modernizes the cov picking and adds some error checking.
@mdclarke can you try it?
=> FIX: Fix concat

mnefun/_mnefun.py, mnefun/_report.py
@mdclarke feel free to give this a chance with the problematic datasets when you get a chance.
=> FIX: Allow close coils

examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_report.py, mnefun/stats.py
Has fixes for latest rank support in MNE, plus a tweak for `hotelling`.
@ktavabi if you have been using `cov_method='shrunk'` it should work better now.
=> FIX: Fixes for cov and hotelling

mnefun/stats.py
@mdclarke I split this into two commits to help readability: the first just refactors things to use the same mu/sigma->p value computation in both `hotelling` functions; the second refactors both functions to allow a two-sample Hotelling T2 test. Feel free to look at the two separately, or if it's easier, the changes in this PR in total directly.
=> WIP: Hotelling for two samples

examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_report.py
Some fixes to allow `proj_meg='combined'` for slightly cleaner proj w/SSS'ed data.
=> FIX: Combined projs

mnefun/__init__.py, mnefun/_mnefun.py, mnefun/_reorder.py, mnefun/_report.py
Generalizes processing a little bit and makes the messages more informative.
=> ENH: Better messages during processing

mnefun/__init__.py, mnefun/_mnefun.py, mnefun/_reorder.py
I often point people to this as a ref for the Glasser parcellation
https://images.nature.com/full/nature-assets/nature/journal/v536/n7615/extref/nature18933-s3.pdf
This gives the int->name mapping for this.
Also includes a simplification of the reordering code.
=> ENH: Add HCPMMP mapping

mnefun/_mnefun.py
Fixes minor bug in passing rejection criteria during SSP computation.
=> FIX: Rejection criteria bug in raw SSP routine

mnefun/_mnefun.py
@larsoner this should fix #246 once d650fbdd30c303aad3fd8ac2f6281448d92968df is merged.
=> FIX auto bad channel selection

examples/funloc/analysis_fun.py, mnefun/_mnefun.py
WIP to address #250 @larsoner please review.
=> WIP Add Maxfilter autobad channel detection

examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_report.py, mnefun/stats.py
@ktavabi hopefully this will make your life easier working with template + volumetric source spaces.
=> ENH: Add support for volume source spaces

mnefun/_mnefun.py
Closes #255.
Produces for `funloc` during the forward calculation step:
```
Generating forward models. 
Creating forward solution(s) using a 3-layer BEM for subj_01... (dig<->MRI 2.1 mm)
Creating forward solution(s) using a 3-layer BEM for subj_02... (dig<->MRI 2.4 mm)
(0:00:30.995)
Done
```
@ktavabi want to try it on some of your datasets? If you update MNE to latest and re-run the forward step you should see these outputs.
=> ENH: Add dig<->MRI distances

mnefun/_mnefun.py, mnefun/_report.py
Improves checks for MaxFilter position validity, fixes a bug with annotation checks, and improves `flat` to allow `dict` entries.
=> FIX: Better checks for validity

examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_report.py
Adds `drop_log` plotting and fixes a problem with `fit_data` being `None` in report.
=> ENH: Add drop_log plotting

mnefun/_mnefun.py
Alright, here's this PR to address the calc_twa_hp issue. I tested this fix against a couple of the PREK subjects that were having issues, and it looks good. Eric, let me know if you think this looks good. 
Closes #261
=> deduplicating time points from replaced head positions

.gitignore, .travis.yml, Makefile, codecov.yml, examples/funloc/analysis_fun.py, mnefun/_mnefun.py, mnefun/_paths.py, mnefun/_report.py, mnefun/bin/__init__.py, mnefun/bin/_plot_chpi_snr.py, mnefun/bin/_simulate_movement.py, mnefun/conftest.py, mnefun/stats.py, mnefun/tests/test_events.py, mnefun/tests/test_save_epochs.py, setup.cfg, setup.py
I decided to tackle YAML first, and let that guide the file separation.
But before that I decided to try to implement some CI / unit tests, since I'll want them to ensure YAML completeness.
=> MAINT: Spin up CIs and unit-tests

mnefun/_reorder.py, mnefun/tests/test_reorder.py
=> FIX: Reorder

examples/funloc/funloc_params.yml, mnefun/_forward.py, mnefun/_inverse.py, mnefun/_paths.py, mnefun/_report.py, mnefun/_sss.py
=> FIX: Make reports work for ERM-cov-only

doc/python_reference.rst, doc/whats_new.rst, mnefun/__init__.py, mnefun/_atlas.py, mnefun/tests/test_atlas.py
WIP for extracting volumetric ROIs. So far just have the atlas names in place.
=> ENH: Add volume ROI extractor

doc/overview.rst, doc/whats_new.rst, examples/funloc/analysis_fun.py, examples/funloc/funloc_params.yml, mnefun/_flow.py, mnefun/_mnefun.py, mnefun/_report.py, mnefun/_sss.py, mnefun/_viz.py, mnefun/bin/_acq_qa.py, mnefun/data/canonical.yml
Add `find_bad_channels_maxwell` to `mnefun` alongside some Report fixes.
=> MRG, ENH: Add Python automatic bad channel path

doc/overview.rst, mnefun/_report.py, mnefun/_sss.py
Going through GenZ reports with the split evokeds, it made more sense to turn some things into sliders and join some plots.
WIP until we see if this is good enough for inspection...
=> WIP, ENH: Streamline report comparisons

mnefun/_report.py, mnefun/_sss.py
@nordme this is what the `funloc` data look like with this PR:
WDYT? Solid lines are all projected traces at the same scale. Dashed are each normalized individually. So for the EOG you can see that the first component is much larger than the other two.
Closes #296
=> ENH: Add counts and channel name

doc/overview.rst, doc/whats_new.rst, examples/funloc/analysis_fun.py, examples/funloc/funloc_params.yml, examples/funloc/score.py, mnefun/_epoching.py, mnefun/_inverse.py, mnefun/_mnefun.py, mnefun/_report.py, mnefun/_ssp.py, mnefun/_sss.py, mnefun/_yaml.py, mnefun/data/canonical.yml, mnefun/tests/test_documented.py
Allow adding additional entries to the report at the beginning and end:
@NeuroLaunch will this help with F2F? This is a super simple example but in principle you can use any of the `report` functions you want, including the `add_figs_to_section`, etc.
=> MRG, ENH: Add report hooks

mnefun/_sss.py
Just a little wrapper for the impending 0.21 release
=> ENH: Wrapper for dep

doc/overview.rst, mnefun/_mnefun.py, mnefun/_sss.py, mnefun/_yaml.py, mnefun/data/canonical.yml
=> ENH: Add option to specify t_window in filter_chpi

doc/overview.rst, examples/funloc/funloc_params.yml, mnefun/_mnefun.py, mnefun/_ssp.py, mnefun/_sss.py, mnefun/_yaml.py, mnefun/data/canonical.yml
@nordme feel free to give this a try, hopefully it makes things flexible enough!
=> ENH: Add options for HEOG/VEOG

.travis.yml, doc/python_reference.rst, mnefun/__init__.py, mnefun/_utils.py
@mdclarke feel free to try it! I recommend backing up your `subjects_dir` and `-trans.fif` files just in case something goes wrong, but in theory this should work. Afterward you'll need to regenerate all fwd/inv/stcs.
=> ENH: Add ANTS conversion function

mnefun/_ssp.py
=> fix: parameter order

mnefun/_report.py
Closes #332
@ktavabi can you see if it fixes your problem?
=> FIX: No singleton times

mnefun/_cov.py
=> Use bmin and bmax for covariance calculation to match docs

doc/overview.rst, doc/whats_new.rst, mnefun/_cov.py, mnefun/_epoching.py, mnefun/_fetching.py, mnefun/_mnefun.py, mnefun/_report.py, mnefun/_scoring.py, mnefun/_ssp.py, mnefun/_status.py, mnefun/data/canonical.yml, mnefun/tests/test_save_epochs.py, setup.cfg
Completely untested, feel free to test @drammock ! In theory you should get a nice `print` statement when you pass a `str`.
=> ENH: Add support for regex reject by annot

mnefun/_fix.py, mnefun/_report.py
A minor fix for badbaby, where sometimes there are no evokeds of any type in the file.
=> FIX: Fix for missing evoked condition

doc/whats_new.rst, mnefun/_epoching.py
A hopefully straightforward improvement to `match_fun` support to allow `numbers` to be passed in, too.
=> ENH: Better match_fun support

mnefun/_sss.py, mnefun/_viz.py
=> Depracation error

mnefun/_report.py
Closes https://github.com/ktavabi/badbaby/issues/15
@ktavabi can you give it a try? There might be other errors down the line, but I think this should fix your empty-report issue.
=> BUG: Fix handling of empty evoked

mnefun/bin/_acq_qa.py
@nordme this allowed me to start report generation again, it's currently running
=> FIX: Fix report generation

examples/funloc/funloc_params.yml, examples/funloc/score.py, mnefun/_report.py, mnefun/_sss.py
Updates report generation for latest MNE-Python `main` where the `add_*` functions we were using have been deprecated.
=> MAINT: Update for 1.0

mnefun/__init__.py, mnefun/_cov.py, mnefun/_epoching.py, mnefun/_sss.py, mnefun/_utils.py, mnefun/_viz.py, setup.py
Fixes a bunch of compatibility bugs with the upcoming MNE-Python 1.0 release
=> BUG: Fix bugs with MNE 1.0

.circleci/config.yml, mnefun/_sss.py
Fix for deprecation of `annotate_flat`
=> FIX: Fix for latest MNE
