LABSN/mnefun

- mnefun/_mnefun.py
@Eric89GXL I got a memory usage warning about too many open `pyplot` windows during psd plotting for a large group of subjects. This is the fastest way I know to make it go away. LMKWYT.
> FIX:close psd plotting window to prevent memory consumption

- mnefun/_status.py
@Eric89GXL caught this bug trying to `print_status` as a function of `run_indices`; instead of using individual subject's runs list the entire group list of list was being passed to `get_raw_fnames` causing empty lists of files to be returned. This fixes the case for a list of runs list and works with example script.
> FIX:status reporting

- mnefun/__init__.py
- mnefun/_mnefun.py
@kambysese can you have a look?
@mdclarke @staulu you should be able to do this:
```
import numpy as np
from scipy import linalg
import mne
from mnefun import info_sss_basis
data_path = mne.datasets.sample.data_path()
evoked = mne.read_evokeds(data_path + '/MEG/sample/sample_audvis-ave.fif')[0]
evoked = evoked.pick_types(meg=True)  # only look at MEG channels
S = info_sss_basis(evoked.info)
sing = linalg.svdvals(S)
print('Condition before proj:  %s' % (sing[0] / sing[-1],))
proj_op = mne.io.proj.make_projector_info(evoked.info)[0]
S_proj = np.dot(proj_op, S)
sing = linalg.svdvals(S_proj)
print('Condition after proj:   %s' % (sing[0] / sing[-1],))
```
And see:
```
Condition before proj:  59.0775421459
Condition after proj:   135.880057672
```
> ENH: Add info SSS basis

- mnefun/__init__.py
- mnefun/_mnefun.py
cc @staulu @mdclarke on this branch you should be able to this:
```
import os.path as op
import mne
from mnefun import plot_reconstruction
data_path = mne.datasets.sample.data_path()
raw = mne.io.read_raw_fif(op.join(data_path, 'MEG', 'sample',
'sample_audvis_raw.fif'), preload=True)
raw.pick_types(meg=True, eeg=False, eog=True, stim=True, exclude=())
events = mne.find_events(raw, 'STI 014')
raw.add_proj(mne.preprocessing.compute_proj_eog(raw)[0])
raw.add_proj(mne.preprocessing.compute_proj_ecg(raw)[0])
epochs = mne.Epochs(raw, events, {'Left auditory': 1}, -0.2, 0.5,
baseline=(None, 0), proj='delayed',
reject=dict(grad=4000e-13, mag=4e-12, eog=150e-6))
evoked = epochs.average()
plot_reconstruction(evoked)
```
And obtain this:
@mdclarke let me know if it works for you. I expect that we'll …
> ENH: Add reconstruction

- examples/funloc/analysis_fun.py
- mnefun/_mnefun.py
@larsoner currently this WIP plots SSP projection topographies of artifacts for MEG sensors and saves figure in `sss_pca_fif` directory. I have two questions:
1. Does `mne.viz.plot_projs_topomap` already handle multiple projection components across channel types e.g., if I request 2 SSP projectors for Grad and 1 projector for Mags will the program plot accordingly
2. How would you advise dealing with EEG projections? As is `mne.viz.plot_projs_topomap` returns a RT error because it cannot find appropriate EEG layout in funloc data. 
LMKWYT.
> WIP:plot artifact SSP topographies and save.

- mnefun/_mnefun.py
This PR:
1. Adds a fourth argument to the `trans_to` tuple, which is a forward(+)/backward(-) head rotation, e.g. `(0., 0., 0.04, -30)` will rotate the head backward 30 degrees.
2. Allows setting `subjects_dir` that will be used to find the structurals.
3. Fixes processing when `STI101` is the only trigger channel available. @mdclarke can you confirm this fixes #195 for you?
Closes #195.
> FIX: trans_to, subjects_dir, extract_expyfun_events

- examples/funloc/analysis_fun.py
- mnefun/_mnefun.py
This adds an option to average epochs when computing EOG and ECG projectors. In some testing this seems to work a little bit better.
@ktavabi at some point you might want to try this on your data. In the meantime the default remains `False`, which is the same as it was before.
> ENH: Add projector averaging

- mnefun/_mnefun.py
Two small tweaks to follow symlinks when copying files to run MaxFilter (useful in case e.g. files were not named properly originally and links are used).
> FIX: Follow symlinks when doing positions

- examples/funloc/analysis_fun.py
- mnefun/_mnefun.py
- mnefun/_report.py
Functionality to `mnefun` (@larsoner):
To `mnefun` report:
For now, not adding the warning for large ExG deflections since hopefully this will be automatically handled by discarding annotated segments now.
> FIX: Fix report and ecg

- examples/funloc/analysis_fun.py
- mnefun/_mnefun.py
Enable user to use CV rejection criteria in autoreject module during automatic bad channel selection routine:
- Use pre-computed rejection criteria if the container `h5` file corresponding to epochs file exists OR
- Use Autoreject to compute criteria on the fly
-  If neither option is available fall back to the user-defined rejection criteria. 
@larsoner LMKWYT
> ENH: Use cross validated rejection criteria for bad channel selection

- examples/funloc/analysis_fun.py
- mnefun/_mnefun.py
- mnefun/_report.py
This code makes a few important changes:
1. When calculating the `head_pos` using MaxFilter in `master`, the implicit bad option was `-autobad on` (MF default). Now we set `-autobad off` and pass our explicit bad list. This will be combined with MF autobad channels list if and only if `params.mf_autobad = True`.
2. When calculating our estimates of the number of good HPI coils in Python, the same list of bad channels is now used that was used during head position estimation (before we didn't set any bads!). This might explain discrepancies where MF has been able to calculate the head position just fine, but our Python-based number-of-good-cHPI-coil counts were less than 3.
3. Makes some minor fixes about when to replace MF position values (though after point (1) above this was no longer …
> BUG: Dont use autobad, pass bads explicitly

- .gitignore
- examples/funloc/analysis_fun.py
- mnefun/_mnefun.py
- mnefun/_report.py
- mnefun/misc.py
1. Unifies how `epochs` are created in `save_epochs` and in `gen_covariances`. Critically the `reject_by_annotation` param differed, which seemed to be breaking the rank estimation.
2. Cleans up the decisions about when the annotation code prints.
3. Fixes a documentation bug about `int_order` vs `ext_order` for infant data.
4. Allows setting `params.cov_rank_tol` to something higher than the default (1e-6).
@nordme @drammock can you see if (1) this fixes your error?
Even after (1), though, I found that some conditions had a bit of a whitening problem in the reports, which could be fixed by (4), namely setting `params.cov_rank_tol = 1e-2`. This seems a bit high, though, so alternatively using `params.cov_method='shrunk'` (instead of `'empirical'`) might be a better choice, as it also …
> FIX: Minor fixes

- mnefun/_sss.py
Warnings about cropping annotations should be disabled for empty-room files. They will likely be cropped.
> FIX: Dont emit warning when processing empty-room files

- doc/whats_new.rst
- examples/funloc/funloc_params.yml
- mnefun/_report.py
A few comments:
- As @larsoner suggested, I used the global field power from the evoked object; for the source section, if that was already calculated for the sensor section, then I reused the 'times' for that particular analysis file / condition(name) combination (i.e. memoization)
- I went with the usual standard-deviation approach for gfp, but sqrt of the mean of the square is another way to go that takes into account mean activity across channels; I don't think the differences were that large, especially for the largest peaks
- There are other peak-finding functions, such as _find_peaks (and _process_times) in viz.utils; however, I think the prominence approach is more robust
- Per _process_times(), I assumed a modest number of peaks across the gfp, taking the most "prominent" and …
> MRG, ENH:  Use peak times for sensor and source plots in .html reports

- mnefun/_cov.py
- mnefun/_epoching.py
- mnefun/_scoring.py
- mnefun/_status.py
- mnefun/_utils.py
I tested this with 1) the usual funloc examples with non-split raw files and only a single run (subj_01 and subj_02); 2) a pseudo "subj_03" (also non-split), with a second run created by duplicating and clipping the original raw fif data; 3) a f2f subject with split raw files (2 file parts) encompassing a single run.  Note, I did not test it on a subject with split raw files AND multiple runs, but the code should allow for it.
Also corrected minor issues in other files, but please see commit notes.
> FIX: split-file issue with epoching and covariance processing (closes 287)

- doc/overview.rst
- doc/whats_new.rst
- examples/funloc/funloc_params.yml
- mnefun/_epoching.py
- mnefun/_mnefun.py
- mnefun/_report.py
- mnefun/data/canonical.yml
- mnefun/tests/test_documented.py
1. Forces `cov` to be provided when `peaks='times'` because the `rank` is needed to compute the GFP. I don't think this is too onerous anyway...
2. Adds `every_other` support, plus plotting in `report` if they're available in the Evoked
@NeuroLaunch can you try this on Alexis's data?
Closes #288
> ENH: Add every_other

- doc/overview.rst
- examples/funloc/funloc_params.yml
- mnefun/_cov.py
- mnefun/_inverse.py
- mnefun/_mnefun.py
- mnefun/_paths.py
- mnefun/_report.py
- mnefun/_viz.py
- mnefun/data/canonical.yml
Requires some upstream changes to MNE to handle `compute_rank` properly. Going to keep this open while debugging GenZ cov issues.
Also moves toward making MNE_3D_BACKEND=pyvista usable with reports.
> MRG, FIX: Rank

- .travis.yml
- doc/whats_new.rst
- mnefun/_epoching.py
- mnefun/_report.py
- mnefun/_ssp.py
FYI @NeuroLaunch if you rerun the `apply_ssp` and `write_epochs` steps, your `-epo.fif` and `-ave.fif` files should end up with the cHPI channels included. At least with the `funloc` data these changes make it work.
> MRG, FIX: Fix errant picking of only data channels

- doc/whats_new.rst
- mnefun/_epoching.py
- mnefun/_report.py
- mnefun/_sss.py
This pull request fixes an SSS processing issue with poor coil amplitude fits (goodness-of-fits << 0.90) when coil frequencies are too close to harmonics of the line frequency.
- Removed a redundant `t_window` calculation in _head_pos_annot()
- Added option to return `t_window` value from call to _get_fit_data(), for backward compatibility
- Fixed an occasional problem where raw.time_as_index() returns a negative value other than -1 (the mne-python method shouldn't do this, but the fix here in mnefun should not cause conflicts)
- Caveat: The `t_window` value used for filter_chpi() and other routines may not be the same as `t_window` calculated for _get_fit_data(); this seems not be a problem
- Code was tested with 1 subject having high coil frequencies (700-900+ Hz) and 1 subject having …
> FIX: Adjust coil time window to allow for line harmonics

- mnefun/__init__.py
- mnefun/_inverse.py
- mnefun/_utils.py
@mdclarke can you see if this works with your data? This script for me:
<details>
```
import numpy as np
import mne
from mnefun import make_dipole_projectors
data_path = mne.datasets.sample.data_path()
subjects_dir = data_path + '/subjects'
fname_ave = data_path + '/MEG/sample/sample_audvis-ave.fif'
fname_cov = data_path + '/MEG/sample/sample_audvis-cov.fif'
fname_fwd = data_path + '/MEG/sample/sample_audvis-meg-eeg-oct-6-fwd.fif'
fname_bem = subjects_dir + '/sample/bem/sample-5120-5120-5120-bem-sol.fif'
fname_trans = data_path + '/MEG/sample/sample_audvis_raw-trans.fif'
evoked = mne.read_evokeds(fname_ave, condition='Right Auditory',
baseline=(None, 0))
print(evoked)
fwd = mne.read_forward_solution(fname_fwd)
cov = mne.read_cov(fname_cov)
dipoles, residual = …
```
> ENH: Add make_dipole_projectors

- doc/overview.rst
The docs say "proportion" but what is actually compared is just the raw number, as far as I can tell from the code here:
https://github.com/LABSN/mnefun/blob/4885000a57fb61f0ea3cd01e65dcd327faf557f5/mnefun/_ssp.py#L200-L208
I think this is the right fix given that the default is "10" (i.e., not a proportion), but LMK if you'd rather I leave the docs alone and fix the code / default.
> proportion → number

- doc/overview.rst
- doc/whats_new.rst
- mnefun/_cov.py
- mnefun/_epoching.py
- mnefun/_mnefun.py
- mnefun/_utils.py
Useful for @ktavabi who has data sampled at 1800 and 1200 Hz, allowing `decim=300.` is a lot nicer than having to pass a list of decim values. @nordme @mdclarke can you look as well, as it might be relevant to you, too? Some of your data might be this way, not sure.
> ENH: Allow float decim as dest

- doc/overview.rst
- doc/whats_new.rst
- examples/funloc/funloc_params.yml
- mnefun/_mnefun.py
- mnefun/_report.py
- mnefun/_ssp.py
- mnefun/_sss.py
- mnefun/data/canonical.yml
Adds `eSSS` with optional band-pass support to `mnefun`. If `params.erm_proj_as_ess = True` then it will use `proj_nums[2]` for a given subject to compute empty-room projectors after band-pass filtering between `params.erm_proj_hp_cut` and `params.erm_proj_lp_cut`. You'll probably need to set `params.erm_proj_reject = {'mag': 5.e-11, 'grad': 1.5e-9}` or something similar since the empty-room data can be pretty noisy.
@NeuroLaunch @nordme @mdclarke (I can't remember who all had the issue) feel free to try this to see if it helps with any 30 Hz frequency bumps you see. I'm not 100% convinced that the bad channels are handled properly here, but basically it uses `raw_fif/subj_prebad.txt` to choose bad channels as these will be marked bad for *all* files that will be processed by SSS. So …
> ENH: Add eSSS

- doc/overview.rst
- doc/whats_new.rst
- mnefun/_cov.py
- mnefun/_epoching.py
- mnefun/_mnefun.py
- mnefun/_scoring.py
- mnefun/_yaml.py
- mnefun/data/canonical.yml
Fixes #319 
Partly this PR fixes an error in _\_scoring.py:\_read_events()_ when two events of different ids have the same timestamp.  The simplest workaround would be to pull in only the events that are to be later processed.  At the suggestion of @larsoner I retained existing code for picking events for covariance estimation via a user-defined function, and ported a similar step for the auto_rejection step.  For convenience (e.g. to overcome the double-timestamp issue), the string "restrict" can be used instead of the user-defined picking function; this is interpreted simply as using the events already chosen for processing via `params.in_numbers`.  After the picking, an error is given if repeated timestamps are found.
I think this method gives the most flexibility for choosing events …
> FIX/ENH: Event picking for autoreject + epoching

- doc/overview.rst
- doc/whats_new.rst
- mnefun/_fetching.py
- mnefun/_mnefun.py
- mnefun/_paths.py
- mnefun/_scoring.py
- mnefun/data/canonical.yml
1. If there are multiple sets of files discovered, it's a problem for `fetch_raw=True`. I am hitting this with GenZ for example where some preprocessing was done in the same folder as the acquisition files on `brainstudio`, which means two sets of "original" `_raw.fif` files are found. This adds an `acq_exclude` that allows a list of substrings to look for to exclude. In principle this might also help if a subject is run twice on a given experiment -- you can exclude their unused/old acquisition by folder name (run date) for example.
2. Tweaks the `rsync` command to be NFS-friendly by not trying to set folder mtime and by not being strict about permissions set on the transferred files.
> BUG: Handle additional entries

- mnefun/_epoching.py
- mnefun/_ssp.py
helpful when running on a headless server...  currently things hang with a `qt.qpa.xcb: QXcbConnection: XCB error: 128 (Unknown), sequence: 417, resource id: 0, major code: 131 (Unknown), minor code: 2` and the `RuntimeError` with the helpful message never appears.
> suppress plots during _raise_bad_epochs

- doc/conf.py
- doc/overview.rst
- mnefun/_cov.py
- mnefun/_epoching.py
- mnefun/_utils.py
allows regex-based `reject_epochs_by_annot` when epoching during covariance computation
> Fix: use reject by annot regex during cov step

- doc/whats_new.rst
- mnefun/_cov.py
closes #349 
Waiting for confirmation from @larsoner that this is the right fix, but it's an easy enough fix that I figured I'd tee it up anyway just in case.
> use delayed proj when epoching during cov computation

- mnefun/_epoching.py
- mnefun/_report.py
mnefun/_reports began throwing an error when trying to concatenate raw files for the purpose of plots such as the raw segments and raw psd plots. Apparently, mne's raw.info checking before concatenation has become more stringent. 
This PR adds an argument to the `_concat_resamp_raws` function called `set_dev_head_t`. Default is `False`, but if `True`, `raw.info['dev_head_t']` from the first raw is used for all subsequent raws. 
@larsoner This is working well for the data I've tested it on (the new Genz data).
> _concat_resamp_raws fix

- .circleci/config.yml
- .github/workflows/tests.yml
- mnefun/_sss.py
Today I hit
```
NameError: name 'mark_flat' is not defined
> /opt/mne/fun/mnefun/_sss.py(689)_python_autobad()
687     del skip_stop, skip_start
688     picks_meg = pick_types(raw.info, meg=True)
--> 689     mark_flat(raw, picks=picks_meg, verbose=False)
```
because `try: mne.preprocessing.annotate_amplitude` succeeded, but then it was never used in defining `mark_flat` because the `else` clause was wrongly coded as an `except` clause.
> fix except -> else when importing for mark_flat

- mnefun/_forward.py
- mnefun/_report.py
I think good_hpi_count, raw_segments, and psd under mnefun._reports could all use some help. 
I'm starting with tossing the the mne.fixes call from good_hpi_count (`time_kwargs` is unused).
> Update mnefun._reports to work with current mne-python
